name: Pre-commit Hooks Check

on:
  workflow_call:

jobs:
  pre-commit-check:
    name: main
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      # Step 3: Install Pre-commit
      - name: Install Pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      # Step 4: Run Pre-commit Hooks
      - name: Run Pre-commit
        run: |
          pre-commit install
          pre-commit run --all-files
